[exts]
image = ["jpg", "jpeg", "png", "webp"]
video = ["gif", "mkv", "mp4", "webm"]

[shortcuts]
prev                    = "ArrowLeft"
next                    = "ArrowRight"
pan_up                  = "ArrowUp"
pan_down                = "ArrowDown"
fit_width_if_default    = "ArrowUp"
first                   = "Home"
last                    = "End"
fullscreen              = "F"
exit_fullscreen_or_quit = "Escape"
toggle_pause            = "Space"
quit                    = "Q"
toggle_display_mode     = "Backspace"

[shortcuts.sort]
FileName         = "F1"
ModificationDate = "F2"
Size             = "F3"

[shortcuts.view_modes]
FitWindow  = "Num1"
FitWidth   = "Num2"
ActualSize = "Num3"

[controls]
zoom_sensitivity         = 200.0
scroll_sensitivity       = 2.0
keyboard_pan_sensitivity = 0.2
keyboard_pan_smooth      = 0.25
